/* ============================================================
   TOGA — dados/juizes-tjce.js : A MAGISTRATURA CEARENSE
   ------------------------------------------------------------
   Amostra da Relação de Magistrados do TJCE (Corregedoria
   Geral da Justiça, atualizada até o DJ de 02/09/2025),
   fornecida pelo autor. Usada para povoar a plateia de
   eventos da ESMEC com juízas e juízes REAIS — homenagem
   institucional: nome + lotação + falas elogiosas/neutras,
   no mesmo padrão dos demais homenageados do jogo.

   sortearJuizes(n): devolve n entradas sem repetição.
   ============================================================ */

window.TOGA = window.TOGA || {};

TOGA.juizesTJCE = (function () {

  /* o palestrante do programa Simples e Mágico */
  const PALESTRANTE = {
    nome: "Luis Gustavo Montezuma Herbster",
    lotacao: "2ª Vara Criminal da Comarca de Quixadá"
  };

  const LISTA = [
    { nome: "Abraão Tiago Costa e Melo", lotacao: "6ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Aclécio Sandro de Oliveira", lotacao: "Vara Única da Comarca de Cedro" },
    { nome: "Ademar da Silva Lima", lotacao: "9ª Vara de Família de Fortaleza" },
    { nome: "Adriana Aguiar Magalhães", lotacao: "5ª Vara Criminal de Fortaleza" },
    { nome: "Adriano Pontes Aragão", lotacao: "15ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Adriano Ribeiro Furtado Barbosa", lotacao: "Vara de Delitos de Organizações Criminosas de Fortaleza" },
    { nome: "Agenor Studart Neto", lotacao: "16ª Vara Cível de Fortaleza" },
    { nome: "Airton Jorge de Sá Filho", lotacao: "Juizado Especial da Comarca de Crateús" },
    { nome: "Alda Maria Holanda Leite", lotacao: "3ª Vara da Infância e Juventude de Fortaleza" },
    { nome: "Aldenor Sombra de Oliveira", lotacao: "3ª Vara Cível da Comarca de Sobral" },
    { nome: "Alexandre Santos Bezerra Sá", lotacao: "Juizado Auxiliar Privativo da 4ª Vara do Júri de Fortaleza" },
    { nome: "Alexsandra Lacerda Batista Brito", lotacao: "2ª Vara de Família e Sucessões de Juazeiro do Norte" },
    { nome: "Alisson do Valle Simeão", lotacao: "6º Juizado Auxiliar das Varas Cíveis de Fortaleza" },
    { nome: "Allan Augusto do Nascimento", lotacao: "Vara Única da Comarca de Chaval" },
    { nome: "Amaiara Cisne Gomes", lotacao: "4ª Vara Criminal da Comarca de Sobral" },
    { nome: "Ana Carolina Montenegro Cavalcanti", lotacao: "10ª Vara Cível de Fortaleza" },
    { nome: "Ana Célia Pinho Carneiro", lotacao: "1º Juizado Auxiliar da 3ª Zona" },
    { nome: "Ana Celina Monte Studart Gurgel Carneiro", lotacao: "1ª Vara da Comarca de Acaraú" },
    { nome: "Ana Cláudia Gomes de Melo", lotacao: "3ª Vara de Sucessões de Fortaleza" },
    { nome: "Ana Clévia Viana de Souza", lotacao: "Vara da Fazenda Pública de Caucaia" },
    { nome: "Ana Cristina de Pontes Lima Esmeraldo", lotacao: "3ª Turma Recursal da Fazenda Pública" },
    { nome: "Ana Izabel de Andrade Lima Pontes", lotacao: "2ª Vara Cível da Comarca de Maranguape" },
    { nome: "Ana Kayrena da Silva Freitas", lotacao: "8ª Vara Cível de Fortaleza" },
    { nome: "Ana Luiza Craveiro Barreira", lotacao: "9ª Vara Cível de Fortaleza" },
    { nome: "Ana Raquel Colares dos Santos", lotacao: "26ª Vara Cível de Fortaleza" },
    { nome: "Anderson Alexandre Nascimento Silva", lotacao: "Vara Única da Comarca de Ibiapina" },
    { nome: "André Aguiar Magalhães", lotacao: "Juizado Especial da Fazenda Pública" },
    { nome: "André Arruda Veras", lotacao: "2ª Vara da Comarca de Trairi" },
    { nome: "André Aziz Ferrareto Neme", lotacao: "1ª Vara da Comarca de Granja" },
    { nome: "André de Carvalho Amorim", lotacao: "Juizado Especial da Comarca de Tianguá" },
    { nome: "André Teixeira Gurgel", lotacao: "7º Juizado Auxiliar das Varas Criminais" },
    { nome: "Andréa Pimenta Freitas Pinto", lotacao: "1ª Vara da Comarca de Fortaleza" },
    { nome: "Angelo Bianco Vettorazzi", lotacao: "Juizado Especial da Comarca de Crato" },
    { nome: "Anna Carolina Freitas de Souza Feitosa", lotacao: "1ª Vara da Comarca de Uruburetama" },
    { nome: "Anna Karolina Cordeiro de Araújo Carvalhal", lotacao: "6º Núcleo Regional de Custódia e das Garantias" },
    { nome: "Antonia Cleliane Fernandes Duarte", lotacao: "1ª Vara Cível da Comarca de Eusébio" },
    { nome: "Antonia Dilce Rodrigues Feijão", lotacao: "16º Juizado Especial Cível de Fortaleza" },
    { nome: "Antonia Neuma Mota Moreira Dias", lotacao: "20ª Vara Cível de Fortaleza" },
    { nome: "Antonio Alves de Araújo", lotacao: "1ª Turma Recursal — Juizados Especiais" },
    { nome: "Antonio Carlos Pinheiro Klein Filho", lotacao: "2ª Vara de Delitos de Tráfico de Drogas de Fortaleza" },
    { nome: "Antonio Carneiro Roberto", lotacao: "2º Juizado Especial Cível e Criminal de Sobral" },
    { nome: "Antonio Cristiano de Carvalho Magalhães", lotacao: "4ª Vara Cível de Fortaleza" },
    { nome: "Antonio Edilberto Oliveira Lima", lotacao: "Juizado Auxiliar Privativo da 1ª Vara do Júri" },
    { nome: "Antonio Josimar Almeida Alves", lotacao: "2ª Vara do Júri de Fortaleza" },
    { nome: "Antonio Jurandy Porto Rosa Junior", lotacao: "1ª Vara Cível da Comarca de Maracanaú" },
    { nome: "Antonio Teixeira de Sousa", lotacao: "25ª Vara Cível de Fortaleza" },
    { nome: "Antonio Vandemberg Francelino Freitas", lotacao: "1º Núcleo Regional de Custódia e das Garantias" },
    { nome: "Antonio Washington Frota", lotacao: "1ª Vara Cível da Comarca de Sobral" },
    { nome: "Ariana Cristina de Freitas", lotacao: "5ª Vara de Família de Fortaleza" },
    { nome: "Arthur Moura Costa", lotacao: "6º Núcleo Regional de Custódia e das Garantias" },
    { nome: "Bernardo Raposo Vidal", lotacao: "2ª Vara Cível da Comarca de Baturité" },
    { nome: "Bruna dos Santos Costa Rodrigues", lotacao: "1ª Vara da Comarca de Pacatuba" },
    { nome: "Bruno dos Anjos", lotacao: "Juizado Especial da Comarca de Sobral" },
    { nome: "Bruno Gomes Benigno Sobral", lotacao: "15ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Caio Lima Barroso", lotacao: "Vara Única da Comarca de Caridade" },
    { nome: "Candice Arruda Vasconcelos", lotacao: "Juizado Especial da Comarca de Maracanaú" },
    { nome: "Carla Susiany Alves de Moura", lotacao: "5º Juizado Auxiliar das Varas Criminais de Fortaleza" },
    { nome: "Carlos Eduardo Carvalho Arrais", lotacao: "1ª Vara Cível da Comarca de Iguatu" },
    { nome: "Carlos Eduardo de Oliveira Holanda Junior", lotacao: "1ª Vara Criminal da Comarca de Caucaia" },
    { nome: "Carlos Henrique Garcia de Oliveira", lotacao: "2ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Carlos Rogério Facundo", lotacao: "13ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Carolina Vilela Chaves Marcolino", lotacao: "4ª Vara Criminal de Juazeiro do Norte" },
    { nome: "Cesar de Barros Lima", lotacao: "1ª Vara de São Gonçalo do Amarante" },
    { nome: "Cesar Morel Alcântara", lotacao: "Juizado da Violência Doméstica de Maracanaú" },
    { nome: "Cid Peixoto do Amaral Neto", lotacao: "3ª Vara Cível de Fortaleza" },
    { nome: "Cláudia Waleska Mattos Mascarenhas", lotacao: "6ª Vara Criminal de Fortaleza" },
    { nome: "Cláudio Augusto Marques de Sales", lotacao: "1ª Vara Empresarial e de Recuperação de Empresas" },
    { nome: "Cláudio Ibiapina", lotacao: "33ª Vara Cível de Fortaleza" },
    { nome: "Cleber de Castro Cruz", lotacao: "16ª Vara de Família de Fortaleza" },
    { nome: "Cristiano Rabelo Leitão", lotacao: "37ª Vara Cível de Fortaleza" },
    { nome: "Cristiano Sanches de Carvalho", lotacao: "2ª Vara da Comarca de Trairi" },
    { nome: "Cynthia Pereira Petri Feitosa", lotacao: "Vara Única da Comarca de Aracoiaba" },
    { nome: "Daniel Carvalho Carneiro", lotacao: "3ª Vara Empresarial e de Recuperação de Empresas" },
    { nome: "Daniel Gonçalves Gondim", lotacao: "2ª Vara de Família da Comarca de Sobral" },
    { nome: "Daniela Lima da Rocha", lotacao: "Juizado Auxiliar Privativo da 3ª Vara do Júri" },
    { nome: "Danielle Estevam Albuquerque", lotacao: "11ª Vara Cível de Fortaleza" },
    { nome: "Danielle Pontes de Arruda Pinheiro", lotacao: "Vara de Execuções de Penas Alternativas" },
    { nome: "David Fortuna da Mata", lotacao: "4ª Vara de Execuções Fiscais de Fortaleza" },
    { nome: "David Melo Teixeira Sousa", lotacao: "3ª Vara Criminal de Juazeiro do Norte" },
    { nome: "Dayana Cláudia Tavares Barros de Castro", lotacao: "Vara Única da Comarca de Boa Viagem" },
    { nome: "Débora Danielle Pinheiro Ximenes", lotacao: "Vara da Infância e Juventude de Caucaia" },
    { nome: "Demétrio Saker Neto", lotacao: "12ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Denys Karol Martins Santana", lotacao: "1ª Vara Cível da Comarca de Tianguá" },
    { nome: "Diogo Schenatto Irion", lotacao: "1ª Vara da Comarca de Morada Nova" },
    { nome: "Edison Ponte Bandeira de Melo", lotacao: "2ª Unidade dos Juizados Especiais de Caucaia" },
    { nome: "Eduardo André Dantas Silva", lotacao: "Vara Única de Família e Sucessões de Iguatu" },
    { nome: "Eduardo Braga Rocha", lotacao: "18ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Eduardo de Castro Neto", lotacao: "2ª Vara Cível de Fortaleza" },
    { nome: "Elison Pacheco Oliveira Teixeira", lotacao: "4º Juizado Auxiliar dos Juizados Especiais Cíveis" },
    { nome: "Elizabeth Passos Rodrigues Martins", lotacao: "7ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Emílio de Medeiros Viana", lotacao: "10ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Érick José Pinheiro Pimenta", lotacao: "2ª Vara Cível da Comarca de Sobral" },
    { nome: "Érick Omar Soares Araújo", lotacao: "Vara Única Criminal da Comarca de Eusébio" },
    { nome: "Evaldo Lopes Vieira", lotacao: "2ª Turma Recursal — Juizados Especiais" },
    { nome: "Fabiana Silva Felix da Rocha", lotacao: "17ª Vara Cível de Fortaleza" },
    { nome: "Fabiano Damasceno Maia", lotacao: "4ª Vara Cível de Fortaleza" },
    { nome: "Fábio Medeiros Falcão de Andrade", lotacao: "1º Juizado Auxiliar da 7ª Zona" },
    { nome: "Fabrícia Ferreira de Freitas", lotacao: "23ª Vara Cível de Fortaleza" },
    { nome: "Fabrício Vasconcelos Mazza", lotacao: "15ª Vara Criminal de Fortaleza" },
    { nome: "Fabricius Ferreira Silva", lotacao: "1ª Vara Cível de Juazeiro do Norte" },
    { nome: "Fátima Maria Rosa Mendonça", lotacao: "1º Juizado da Violência Doméstica de Fortaleza" },
    { nome: "Fátima Xavier Damasceno", lotacao: "13ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Felipe Augusto Rola Pergentino Maia", lotacao: "4º Juizado Auxiliar das Varas Criminais de Fortaleza" },
    { nome: "Fernanda Rocha Martins", lotacao: "Vara Única da Comarca de Ubajara" },
    { nome: "Fernando Antonio Pacheco Carvalho Filho", lotacao: "4ª Vara das Execuções Penais" },
    { nome: "Fernando Cezar Barbosa de Souza", lotacao: "1ª Vara Cível da Comarca de Fortaleza" },
    { nome: "Fernando de Souza Vicente", lotacao: "Vara da Infância e Juventude de Maracanaú" },
    { nome: "Fernando Luiz Pinheiro Barros", lotacao: "7ª Vara Cível de Fortaleza" },
    { nome: "Flávia Maria Aires Freire Allemão", lotacao: "Núcleo 4.0 — Execuções de Títulos Extrajudiciais" },
    { nome: "Flávia Pessoa Maciel", lotacao: "20ª Unidade de Juizado Especial Criminal de Fortaleza" },
    { nome: "Flávio Luiz Peixoto Marques", lotacao: "2ª Turma Recursal — Juizados Especiais" },
    { nome: "Flávio Vinicius Bastos Sousa", lotacao: "3ª Vara de Delitos de Tráfico de Drogas de Fortaleza" },
    { nome: "Francisca Francy Maria da Costa Farias", lotacao: "13ª Vara Cível de Fortaleza" },
    { nome: "Francisco Anastácio Cavalcante Neto", lotacao: "4º Juizado da Violência Doméstica de Fortaleza" },
    { nome: "Francisco Chagas Barreto Alves", lotacao: "Vara da Fazenda Pública de Fortaleza" },
    { nome: "Francisco das Chagas Gomes", lotacao: "16ª Vara Criminal de Fortaleza" },
    { nome: "Francisco Eduardo Fontenele Batista", lotacao: "2º Juizado Auxiliar das Varas da Fazenda Pública" },
    { nome: "Francisco Eduardo Girão Braga", lotacao: "Juizado Auxiliar da 3ª Zona — sede em Quixadá" },
    { nome: "Francisco Gilmário Barros Lima", lotacao: "3ª Vara do Júri de Fortaleza" },
    { nome: "Francisco Gladyson Pontes Filho", lotacao: "2ª Vara de Execuções Fiscais de Fortaleza" },
    { nome: "Francisco Hilton Domingos de Luna Filho", lotacao: "Vara Única Criminal da Comarca de Aquiraz" },
    { nome: "Francisco Ireilton Bezerra Freire", lotacao: "2ª Vara da Comarca de Tauá" },
    { nome: "Francisco Janailson Pereira Ludugero", lotacao: "Juizado da Violência Doméstica de Sobral" },
    { nome: "Francisco José Mazza Siqueira", lotacao: "2ª Vara Cível de Juazeiro do Norte" },
    { nome: "Francisco Marcelo Alves Nobre", lotacao: "5º Juizado Auxiliar da 5ª Zona" },
    { nome: "Frederico Augusto Costa", lotacao: "1ª Vara Criminal da Comarca de Sobral" },
    { nome: "Frederico Costa Bezerra", lotacao: "1ª Vara da Comarca de Tauá" },
    { nome: "Gabriela Carvalho Azzi", lotacao: "1ª Vara Cível da Comarca de Itapajé" },
    { nome: "Gerana Celly Dantas da Cunha Veríssimo", lotacao: "17ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Gesília Pacheco Cavalcanti", lotacao: "3ª Vara de Execuções Fiscais de Fortaleza" },
    { nome: "Giancarlo Antoniazzi Achutti", lotacao: "12ª Vara de Família de Fortaleza" },
    { nome: "Gilvan Brito Alves Filho", lotacao: "2ª Vara da Comarca de Massapê" },
    { nome: "Giselli Lima de Sousa Tavares", lotacao: "Vara Única da Comarca de Jaguaruana" },
    { nome: "Gonçalo Benício de Melo Neto", lotacao: "2º Juizado Especial Cível de Fortaleza" },
    { nome: "Gúcio Carvalho Coelho", lotacao: "8ª Vara de Família de Fortaleza" },
    { nome: "Gustavo Farias Alves", lotacao: "1ª Vara da Comarca de Acaraú" },
    { nome: "Gustavo Ferreira Mainardes", lotacao: "Vara Única de Santana do Acaraú" },
    { nome: "Gustavo Henrique Cardoso Cavalcante", lotacao: "1ª Vara de Família e Sucessões de Juazeiro do Norte" },
    { nome: "Harbelia Sancho Teixeira", lotacao: "2ª Vara da Comarca de Uruburetama" },
    { nome: "Helga Medved", lotacao: "22ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Henrique Botelho Romcy", lotacao: "8º Juizado Especial Criminal de Fortaleza" },
    { nome: "Henrique Jorge dos Santos Falcão", lotacao: "1ª Vara de Família e Sucessões de Caucaia" },
    { nome: "Henrique Lacerda de Vasconcelos", lotacao: "Vara de Delitos de Organizações Criminosas" },
    { nome: "Hérick Bezerra Tavares", lotacao: "Vara Única da Comarca de Nova Olinda" },
    { nome: "Hugo Gutparakis de Miranda", lotacao: "3º Juizado Auxiliar da 7ª Zona" },
    { nome: "Hyldon Masters Cavalcante Costa", lotacao: "Vara Única da Comarca de Várzea Alegre" },
    { nome: "Iclea Aguiar Araújo Rolim", lotacao: "21ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Isaac de Medeiros Santos", lotacao: "5º Juizado Auxiliar da 5ª Zona — sede em Maracanaú" },
    { nome: "Jamyerson Camara Bezerra", lotacao: "8ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Janaina Graciano de Brito", lotacao: "1ª Vara da Comarca de Horizonte" },
    { nome: "Jhulian Pablo Rocha Faria", lotacao: "2ª Vara da Comarca de Pacatuba" },
    { nome: "João Everardo Matos Biermann", lotacao: "13ª Vara de Fazenda Pública de Fortaleza" },
    { nome: "Jorge Cruz de Carvalho", lotacao: "1ª Vara de Família e Sucessões de Maracanaú" },
    { nome: "Jorge Di Ciero Miranda", lotacao: "34ª Vara Cível de Fortaleza" },
    { nome: "José Batista de Andrade", lotacao: "1ª Vara Cível da Comarca de Crato" },
    { nome: "José Flávio Bezerra Morais", lotacao: "2ª Vara Cível da Comarca de Crato" },
    { nome: "José Gilderlan Lins", lotacao: "Vara Única da Comarca de Aurora" },
    { nome: "José Krentel Ferreira Filho", lotacao: "2ª Vara de Sucessões de Fortaleza" },
    { nome: "José Maria dos Santos Sales", lotacao: "4ª Turma Recursal — Juizados Especiais" },
    { nome: "José Mauro Lima Feitosa", lotacao: "15ª Vara de Família de Fortaleza" },
    { nome: "José Ricardo Costa D'Almeida", lotacao: "6ª Vara de Família de Fortaleza" },
    { nome: "Josias Nunes Vidal", lotacao: "18ª Vara Cível de Fortaleza" },
    { nome: "Juliana Porto Sales", lotacao: "Juizado Auxiliar da 12ª Zona — sede em Aracati" },
    { nome: "Juliana Sampaio de Araújo", lotacao: "2ª Vara da Comarca de Aquiraz" },
    { nome: "Julianne Bezerra Barros Santos", lotacao: "2ª Vara Cível de Aquiraz" },
    { nome: "Juraci de Souza Santos Junior", lotacao: "2ª Vara Criminal da Comarca de Crato" },
    { nome: "Karla Cristina de Oliveira", lotacao: "3º Juizado Auxiliar da Fazenda Pública de Fortaleza" },
    { nome: "Karla Neves Guimarães da Costa Aranha", lotacao: "2ª Vara Criminal da Comarca de Iguatu" },
    { nome: "Kathleen Nicola Kilian", lotacao: "Núcleo de Apoio à Corregedoria de Presídios" },
    { nome: "Klovis Caricio da Cruz Marques", lotacao: "Vara Única da Comarca de Caririaçu" },
    { nome: "Larissa Affonso Mayer", lotacao: "2ª Vara de São Benedito" },
    { nome: "Larissa Braga Costa de Oliveira Lima", lotacao: "2ª Vara Criminal de Juazeiro do Norte" },
    { nome: "Leila Regina Corado Lobato", lotacao: "36ª Vara Cível de Fortaleza" },
    { nome: "Leonardo Afonso Franco de Freitas", lotacao: "Vara de Família e Sucessões do Crato" },
    { nome: "Leopoldina de Andrade Fernandes", lotacao: "1º Juizado de Família, Sucessões e Infância" },
    { nome: "Leslie Anne Maia Campos", lotacao: "Vara Única Criminal da Comarca de Itapipoca" },
    { nome: "Lia Sammia Souza Moreira", lotacao: "1º Juizado Auxiliar das Varas da Fazenda Pública" },
    { nome: "Liana Alencar Correia", lotacao: "1ª Vara Cível da Comarca de Tauá" },
    { nome: "Lucas D'Ávila Alves Brandão", lotacao: "1ª Vara Cível da Comarca de Maranguape" },
    { nome: "Lucas Medeiros de Lima", lotacao: "2ª Vara da Comarca de Itaitinga" },
    { nome: "Lucas Rocha Solon", lotacao: "Vara Única Cível da Comarca de Aracati" },
    { nome: "Lucas Sobreira de Barros Fonseca", lotacao: "Vara Única Criminal da Comarca de Russas" },
    { nome: "Luciana Teixeira de Souza", lotacao: "2ª Vara das Execuções Penais de Fortaleza" },
    { nome: "Luciano Nunes Maia Freire", lotacao: "7º Juizado Auxiliar das Varas Cíveis de Fortaleza" },
    { nome: "Lucimeire Godeiro Costa", lotacao: "21ª Vara Cível de Fortaleza" },
    { nome: "Luis Eduardo Girão Mota", lotacao: "4ª Vara do Júri da Comarca de Fortaleza" },
    { nome: "Luis Sávio de Azevedo Bringel", lotacao: "3º Juizado Auxiliar da 1ª Zona" },
    { nome: "Luiz Augusto de Vasconcelos", lotacao: "1ª Unidade dos Juizados Especiais de Caucaia" },
    { nome: "Luiz Carlos Saraiva Guerra", lotacao: "2º Juizado Auxiliar das Unidades dos Juizados Especiais" },
    { nome: "Luiz Eduardo Viana Pequeno", lotacao: "2ª Vara Cível da Comarca de Maracanaú" },
    { nome: "Luiz Guilherme Costa Pedroso Silva", lotacao: "1ª Vara Cível da Comarca de Itapipoca" },
    { nome: "Luiz Phelipe Fernandes de Freitas Morais", lotacao: "Vara Única da Comarca de Jardim" },
    { nome: "Luzia Ponte de Almeida", lotacao: "1ª Vara de Família da Comarca de Fortaleza" },
    { nome: "Mabel Viana Maciel", lotacao: "Juizado Auxiliar Privativo da 3ª Vara da Infância e Juventude" },
    { nome: "Magno Gomes de Oliveira", lotacao: "4ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Magno Rocha The Mota", lotacao: "Vara de Delitos de Organizações Criminosas de Fortaleza" },
    { nome: "Mantovanni Colares Cavalcante", lotacao: "4ª Vara da Fazenda Pública de Fortaleza" },
    { nome: "Manuel Clístenes de Façanha e Gonçalves", lotacao: "5ª Vara da Infância e Juventude de Fortaleza" },
    { nome: "Marcelino Emílio Maciel Filho", lotacao: "1ª Vara da Comarca de Barbalha" },
    { nome: "Marcelo Roseno de Oliveira", lotacao: "12ª Unidade de Juizado Especial Cível de Fortaleza" },
    { nome: "Marcelo Veiga Vieira", lotacao: "2ª Vara Cível da Comarca de Iguatu" },
    { nome: "Márcia Oliveira Fernandes Menescal de Lima", lotacao: "4ª Turma Recursal — Juizados Especiais" },
    { nome: "Marcelo Freire de Souza", lotacao: "Juizado Auxiliar da 3ª Zona Judiciária — sede em Quixadá" },
    { nome: "Marco Aurélio Monteiro", lotacao: "1ª Vara da Comarca de Redenção" },
    { nome: "Marcos Aurélio Marques Nogueira", lotacao: "1ª Vara do Júri da Comarca de Fortaleza" }
  ];

  /* sorteio sem repetição (embaralha uma cópia e fatia) */
  function sortearJuizes(n) {
    const copia = LISTA.slice();
    for (let i = copia.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const t = copia[i]; copia[i] = copia[j]; copia[j] = t;
    }
    return copia.slice(0, Math.min(n, copia.length));
  }

  return {
    PALESTRANTE: PALESTRANTE,
    LISTA: LISTA,
    sortearJuizes: sortearJuizes,
    total: function () { return LISTA.length; }
  };
})();
